# Site settings
title: 
header-img: img/home-bg.png
email: jordanrumeld@me.com
copyright_name: jordanrumeld
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jordanrumeld
learn_profile: jordanrumeld
email_username: jordanrumeld@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
